name: Continuous Integration
on:
  push:
    branches:
      - main
      - 'feature/**'
  pull_request:
    branches: [main]
permissions:
  contents: read
  actions: read
  checks: write
jobs:
  test:
    name: Test
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 10.0.x
      - name: Run .NET tests
        run: dotnet test --configuration Release --report-trx --results-directory ./TestResults --coverage --coverage-output-format cobertura || true
      - name: .NET test report
        uses: dorny/test-reporter@v3
        if: ${{ !cancelled() }}
        with:
          name: test-results-dotnet-${{ matrix.os }}
          path: "./TestResults/*.trx"
          reporter: dotnet-trx
          fail-on-error: true
      - name: Convert .NET TRX to JUnit
        run: |
          mkdir -p junit
          dotnet tool install -g trx2junit
          trx2junit "./TestResults/*.trx" --output ./junit
      - name: Upload coverage artifacts
        uses: actions/upload-artifact@v6
        with:
          name: Code coverage ${{ matrix.os }}
          path: |
            ./TestResults/*.cobertura.xml
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        if: runner.os == 'Linux'
        with:
          report_type: coverage
          files: "./TestResults/*.cobertura.xml"
          token: ${{ secrets.CODECOV_TOKEN }}
      - name: Upload test results to Codecov
        if: ${{ (!cancelled()) && (runner.os == 'Linux') }}
        uses: codecov/codecov-action@v5
        with:
          report_type: test_results
          files: "junit/*.xml"
          token: ${{ secrets.CODECOV_TOKEN }}
