name: CI

on:
  push:
    branches: [ main, 'release/**', 'feature/**' ]
  pull_request:
    branches: [ main ]

env:
  BUILD_CONFIGURATION: Release

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v6

    - name: Setup .NET
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: '10.x'

    - name: Restore
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration ${{ env.BUILD_CONFIGURATION }} --no-restore /p:PackageOutputPath="${{ github.workspace }}/artifacts"

    - name: Test
      run: dotnet test --configuration ${{ env.BUILD_CONFIGURATION }} --no-build --collect "Code coverage"

    - name: Configure NuGet authentication
      run: dotnet nuget add source --username ${{ github.actor }} --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json"

    - name: Push to GitHub Packages
      if: startsWith(github.ref, 'refs/heads/main')
      run: dotnet nuget push "artifacts/*.nupkg" --source "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json" --api-key ${{ secrets.GITHUB_TOKEN }} --skip-duplicate

    - name: Push to NuGet.org
      if: startsWith(github.ref, 'refs/heads/release/')
      run: dotnet nuget push "artifacts/*.nupkg" --source "https://api.nuget.org/v3/index.json" --api-key ${{ secrets.NUGET_API_KEY }} --skip-duplicate
